name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i

      - run: npm run build
        env:
          CI: false

      - run: pm2 delete tokeny-client

      - run: pm2 start npm --name "tokeny-client" -- run serve --spa

      - run: |
          cd server
          touch .env
          echo VUE_APP_RAWR_KEY='${{ secrets.VUE_APP_RAWR_KEY }}' >> .env
          echo VUE_APP_ROOT_RAILS_URL='${{ secrets.VUE_APP_ROOT_RAILS_URL }}' >> .env
          echo VUE_APP_KOMOJU_SECRET='${{ secrets.VUE_APP_KOMOJU_SECRET }}' >> .env
          cat .env

      - run: |
          pm2 start tokeny-client
          pm2 save
          pm2 resurrect
          sudo service nginx restart
